#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jan 27 12:03:06 2018

('/Users/JenMurphy/Documents/UNIVERSITY/Github/Data-and-Environment---assessment/Messing', wdir='/Users/JenMurphy/Documents/UNIVERSITY/Github/Data-and-Environment---assessment')

@author: JenMurphy
"""
import pandas as pd

#  Read in data - attempt to force European parsing of dates
stores = pd.read_csv('stores.csv', dayfirst=True)
train = pd.read_csv('train.csv', dayfirst=True)
test = pd.read_csv('test.csv', dayfirst=True)
features = pd.read_csv('features.csv', dayfirst=True)

#  Linking of training data
features_stores = pd.merge(features, stores, how = 'left')
merge = pd.merge(train, features_stores, how = 'left')

# create a new variable for a standardised datetime.
# THIS LINE TAKES AGES TO RUN
merge['Newdate']=pd.to_datetime(merge['Date'], dayfirst = True)

#  output to .csv file
merge.to_csv('merge.csv')

#  create a hierarchical index, separate Store, Dept and date
merge.set_index(['Store','Dept','Date'], inplace = True)
merge.sort_index(inplace=True)

# set the hierarchical index
mergeindex = merge.set_index(['Newdate', 'Store', 'Dept'], append=True)


merge['Storestring'] = str(merge['Store'])
merge['Deptstring'] = str(merge['Dept'])

merge['StoreDept'] = "S"+ merge['Storestring']+ "D" +merge['Deptstring']

type(merge['Store'])



pivotmerge = merge.pivot('NewDate','Store','Dept','Weekly_Sales')





#  Does this work?  I dont think so.
groupmerge = merge.groupby(['Store', 'Dept', 'Newdate'])['Weekly_Sales'].sum().unstack('Newdate')
groupmergetranspose = groupmerge.transpose()

pd.pivot_table(merge,index=merge['Newdate'], columns = (merge['Store'],['Dept']), values = merge['Weekly_Sales'])


trymerge = merge.pivot(index='Newdate', columns='Store', values='Weekly_Sales')

#  I want a Df for every department.
for x in range (0,100):
        deptx = merge.loc[merge['Dept']==[x]]

# Pull together descriptive statistics for the variables
merge.describe()


'''
# To reset the index and restore the columns
merge = merge.reset_index()

merge.index

df = merge.groupby('Store','Dept').mean()

merge['year'] = merge.Newdate.dt.year


For year in year
    for dept in dept
        for store in Store,
            
# Truncated datasets for ease of working

#name that I want for each dataframe
namelist = []


for x in range (0,99):
    dept[x] = merge.loc[merge['Dept']== x]


Store1Dept1 = Dept1.loc[Dept1['Store']==1]
Store1 = merge.loc[merge['Store']==1]